### ISSUE TITLE
It breaks when using pnpm (Rush)

### ISSUE THREAD

**Issue by slavafomin** [oclif/plugin-not-found#37]
Hello!

Thank you for this great library!

However, it fails with the error listed below, when used in the monorepo project with pnpm (Rush).

```
TypeError Plugin: my-cli: Cannot read property 'dim' of undefined
    at Object.<anonymous> (…/project/common/temp/node_modules/.pnpm/registry.npmjs.org/@oclif/color/0.0.0/node_modules/@oclif/color/lib/index.js:10:86)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (…/project/common/temp/node_modules/.pnpm/registry.npmjs.org/@oclif/plugin-not-found/1.2.3/node_modules/@oclif/plugin-not-found/lib/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

Probably, you are requiring some dependencies incorrectly or has forgotten to explicitly specify all the used dependencies.

**Comment by slavafomin** [comment]
Looking at `@oclif/color` package, I can see that you are requiring the `chalk` package but hasn't specified it as a dependency in the package manifest.

**Comment by slavafomin** [comment]
`@oclif/color` dependency should be updated to the latest version in order to fix this issue.
